
vame_slot_nms_read <- function() {
  lines <- readLines("R/S4.R")
  lhs_re <- "^[ ]*#+[ ]*slot:"
  value_re <- "[a-z_]+"
  rhs_re <- "[ ]*$"
  slot_nms <- lines[grepl(paste0(lhs_re, value_re, rhs_re), lines)]
  slot_nms <- sub(lhs_re, "", slot_nms)
  slot_nms <- sub(rhs_re, "", slot_nms)
  slot_nms
}
vame_slot_nms <- vame_slot_nms_read()

s1 <- git2r::status()
local({
  lines <- readLines("R/S4.R")
  wh_start <- which(grepl("# start:vame_slot_nms", lines))
  wh_stop <- which(grepl("# stop:vame_slot_nms", lines))
  lines <- c(
    lines[1:wh_start],
    "  # contents generated by dev/01_data.R; do not modify manually",
    sub("[ ]+$", "", paste0("  ", deparse(vame_slot_nms))),
    lines[wh_stop:length(lines)]
  )
  writeLines(lines, "R/S4.R")
})
s2 <- git2r::status()
if (!identical(s1, s2)) {
  git2r::add(path = "R/S4.R")
  git2r::commit(message = "build: run dev/01_data.R")
}
