src_script_path <- function() {
  dir("R", pattern = "S4[.]R$", full.names = TRUE)
}

tgt_script_path <- function() {
  dir("R", pattern = "vame_slot_nms[.]R$", full.names = TRUE)
}

vame_slot_nms_read <- function() {
  lines <- readLines(src_script_path())
  lhs_re <- "^[ ]*#+[ ]*slot:"
  value_re <- "[a-z_]+"
  rhs_re <- "[ ]*$"
  slot_nms <- lines[grepl(paste0(lhs_re, value_re, rhs_re), lines)]
  slot_nms <- sub(lhs_re, "", slot_nms)
  slot_nms <- sub(rhs_re, "", slot_nms)
  slot_nms
}
vame_slot_nms <- vame_slot_nms_read()

s1 <- system2("git", c("--no-pager", "diff", tgt_script_path()), stdout = TRUE)
local({
  lines <- readLines(tgt_script_path())
  wh_start <- which(grepl("# start:vame_slot_nms", lines))
  wh_stop <- which(grepl("# stop:vame_slot_nms", lines))
  lines <- c(
    lines[1:wh_start],
    "  # contents generated by dev/01_data.R; do not modify manually",
    sub("[ ]+$", "", paste0("  ", deparse(vame_slot_nms))),
    lines[wh_stop:length(lines)]
  )
  writeLines(lines, tgt_script_path())
})
Sys.sleep(1.0)
s2 <- system2("git", c("--no-pager", "diff", tgt_script_path()), stdout = TRUE)
if (!identical(s1, s2)) {
  message("Create git commit on ",
          tgt_script_path(),
          " changes? [y/n]")
  if (readline(": ") == "y") {
    git2r::add(path = tgt_script_path())
    git2r::commit(message = "build: run dev/01_data.R")
  }
}
