vame_slot_nms_read <- function() {
  lines <- readLines("./R/05_S4.R")
  lhs_re <- "^[ ]*#+[ ]*slot:"
  value_re <- "[a-z_]+"
  rhs_re <- "[ ]*$"
  slot_nms <- lines[grepl(paste0(lhs_re, value_re, rhs_re), lines)]
  slot_nms <- sub(lhs_re, "", slot_nms)
  slot_nms <- sub(rhs_re, "", slot_nms)
  slot_nms
}
vame_slot_nms <- vame_slot_nms_read()

s1 <- system2("git", c("--no-pager", "diff", "./R/04_vame_slot_nms.R"), stdout = TRUE)
local({
  lines <- readLines("./R/04_vame_slot_nms.R")
  wh_start <- which(grepl("# start:vame_slot_nms", lines))
  wh_stop <- which(grepl("# stop:vame_slot_nms", lines))
  lines <- c(
    lines[1:wh_start],
    "  # contents generated by dev/01_data.R; do not modify manually",
    sub("[ ]+$", "", paste0("  ", deparse(vame_slot_nms))),
    lines[wh_stop:length(lines)]
  )
  writeLines(lines, "./R/04_vame_slot_nms.R")
})
Sys.sleep(1.0)
s2 <- system2("git", c("--no-pager", "diff", "./R/04_vame_slot_nms.R"), stdout = TRUE)
if (!identical(s1, s2)) {
  message("Create git commit on ./R/04_vame_slot_nms.R changes? [y/n]")
  if (readline(": ") == "y") {
    git2r::add(path = "./R/04_vame_slot_nms.R")
    git2r::commit(message = "build: run dev/01_data.R")
  }
}
