vame_slot_nms_get__ <- function() {
  # start:vame_slot_nms
  # contents generated by dev/01_data.R; do not modify manually
  c("var_set_list_get", "var_set_get", "var_set_meta_get", "var_set_meta_set",
  "var_set_meta_get_all", "var_set_rename", "var_set_remove", "var_set_value_space_get",
  "var_set_value_space_set", "var_set_value_space_dt_subset", "var_meta_get",
  "var_meta_set", "var_meta_get_all", "var_rename", "var_remove",
  "var_label_dt_get", "var_label_dt_set", "var_labels_get", "vame_subset",
  "vame_union_append", "vame_category_space_dt_list", "vame_category_space_dt"
  )
  # stop:vame_slot_nms
}
